# Generated by Django 2.1.7 on 2019-04-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RepoGames', '0003_auto_20190421_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='descricao',
            field=models.TextField(null=True),
        ),
    ]
